fn is_palindrome(s: &str) -> bool {
    let s = s.to_lowercase(); // Convert the string to lowercase to handle case-insensitive comparisons
    let reversed = s.chars().rev().collect::<String>(); // Reverse the string
    s == reversed // Check if the original string is equal to its reverse
}

fn main() {
    let test_string1 = "radar";
    let test_string2 = "hello";

    println!("Is '{}' a palindrome? {}", test_string1, is_palindrome(test_string1));
    println!("Is '{}' a palindrome? {}", test_string2, is_palindrome(test_string2));
}
